-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * BS.SALES)
FROM AUTHOR A
INNER JOIN BOOK B
ON B.AUTHOR_ID = A.AUTHOR_ID
INNER JOIN BOOK_SALES BS
ON BS.BOOK_ID = B.BOOK_ID
AND TO_CHAR(BS.SALES_DATE,'YYYY-MM') = '2022-01'
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC

-- 2022-01
-- 저자별, 카테고리별 매출액 : 판매량 * 판매가 를 구하기
