-- 코드를 입력하세요
SELECT OS.YEAR
        , TO_NUMBER(OS.MONTH) AS MONTH
        , UI.GENDER
        , COUNT(DISTINCT OS.USER_ID) AS USERS
FROM (
    SELECT TO_CHAR(SALES_DATE, 'YYYY') AS YEAR
            , TO_CHAR(SALES_DATE, 'MM') AS MONTH
            ,USER_ID
            , PRODUCT_ID
    FROM ONLINE_SALE
    ) OS 
    INNER JOIN (
        SELECT *
        FROM USER_INFO
        WHERE GENDER IS NOT NULL
    ) UI
    ON OS.USER_ID = UI.USER_ID
GROUP BY OS.YEAR, OS.MONTH, UI.GENDER
ORDER BY OS.YEAR, OS.MONTH, UI.GENDER

-- USER_INFO : USER_ID, GENDER(0 남자), AGE, JOINED
-- ONLINE_SALE : ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
-- 년, 월, 성별 별로 상품을 구매한 회원 수 집계 및 오름차순, 성별 정보 없는 경우 제외