-- 코드를 작성해주세요
# 대장균 ECOLI_DATA
# ID , PARENT_ID, SIZE_OF_COLONY: 크기, DIFFERENTIATION_DATE: 분화, GENOTYPE: 형질
# 100 초과 1000이하면 MEDIUM, 1000초과 HIGH
# ID와 SIZE를 출력하는 SQL문 작성
# ID 오름차순
SELECT ID,
CASE
WHEN SIZE_OF_COLONY > 1000 THEN 'HIGH'
WHEN SIZE_OF_COLONY <= 100 THEN 'LOW'
ELSE 'MEDIUM'
END AS SIZE
FROM ECOLI_DATA
ORDER BY ID;