-- 코드를 입력하세요
SELECT FO.PRODUCT_ID, FP.PRODUCT_NAME, SUM(FO.AMOUNT) * FP.PRICE AS TOTAL_SALES
FROM (SELECT PRODUCT_ID, AMOUNT
FROM FOOD_ORDER
WHERE PRODUCE_DATE LIKE '2022-05%') FO
INNER JOIN FOOD_PRODUCT FP
ON FP.PRODUCT_ID = FO.PRODUCT_ID
GROUP BY FO.PRODUCT_ID, FP.PRODUCT_NAME, FP.PRICE
ORDER BY TOTAL_SALES DESC, FO.PRODUCT_ID


-- FOOD_PRODUCT: PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD , CATEGORY, PRICE
-- FOOD_ORDER: ORDER_ID, PRODUCT_ID, AMOUNT, PRODUCE_DATE, IN_DATE, OUT_DATE, FACTORY_ID , WAREHOUSE_ID
-- 생산일자: PRODUCE_DATE : 202205