-- 코드를 입력하세요
SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM APPOINTMENT A
INNER JOIN PATIENT P
ON A.PT_NO = P.PT_NO
INNER JOIN DOCTOR D
ON D.DR_ID = A.MDDR_ID
WHERE TO_CHAR(A.APNT_YMD,'YYYY-MM-DD') = '2022-04-13'
AND A.MCDP_CD = 'CS'
AND A.APNT_CNCL_YN = 'N'
ORDER BY A.APNT_YMD
-- 2022-04-13 취소되지 않은 흉부와과(CS) 예약 내역