SELECT U.USER_ID,U.NICKNAME, SUM(D.PRICE) FROM USED_GOODS_USER U INNER JOIN USED_GOODS_BOARD D ON (U.USER_ID = D.WRITER_ID)
WHERE D.STATUS = 'DONE'
GROUP BY U.USER_ID, U.NICKNAME
HAVING SUM(D.PRICE) >= 700000
ORDER BY SUM(D.PRICE)
## SELECT에 있는 값에는 GROUP BY에 있는 값만 들어갈 수 있다.