-- 코드를 작성해주세요
SELECT SUM(G.SCORE) AS SCORE, G.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_GRADE G
INNER JOIN HR_EMPLOYEES E
ON E.EMP_NO = G.EMP_NO
INNER JOIN HR_DEPARTMENT D
ON D.DEPT_ID = E.DEPT_ID
WHERE G.YEAR = 2022
GROUP BY G.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
ORDER BY SCORE DESC
LIMIT 1