-- 코드를 입력하세요
SELECT FP.CATEGORY, MAX(FP.PRICE) AS MAX_PRICE,
 (  SELECT PRODUCT_NAME
    FROM FOOD_PRODUCT
    WHERE CATEGORY = FP.CATEGORY
    AND PRICE = MAX(FP.PRICE)
 ) AS PRODUCT_NAME
FROM FOOD_PRODUCT FP
GROUP BY FP.CATEGORY
HAVING FP.CATEGORY IN ('과자','국','김치','식용유')
ORDER BY MAX_PRICE DESC

-- PRODUCT_ID : 식품 ID
-- PRODUCT_NAME : 식품 이름
-- PRODUCT_CD : 식품 코드
-- CATEGORY : 식품분류
-- PRICE : 식품 가격